// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MessageTypes
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class LogicalTypeExample : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse("{\"type\":\"record\",\"name\":\"LogicalTypeExample\",\"namespace\":\"MessageTypes\",\"fields\":" +
				"[{\"name\":\"StringValue\",\"type\":\"string\"},{\"name\":\"DateValue\",\"type\":\"int\"},{\"name" +
				"\":\"DecimalValue\",\"type\":\"bytes\"}]}");
		private string _StringValue;
		private int _DateValue;
		private byte[] _DecimalValue;
		public virtual Schema Schema
		{
			get
			{
				return LogicalTypeExample._SCHEMA;
			}
		}
		public string StringValue
		{
			get
			{
				return this._StringValue;
			}
			set
			{
				this._StringValue = value;
			}
		}
		public int DateValue
		{
			get
			{
				return this._DateValue;
			}
			set
			{
				this._DateValue = value;
			}
		}
		public byte[] DecimalValue
		{
			get
			{
				return this._DecimalValue;
			}
			set
			{
				this._DecimalValue = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.StringValue;
			case 1: return this.DateValue;
			case 2: return this.DecimalValue;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.StringValue = (System.String)fieldValue; break;
			case 1: this.DateValue = (System.Int32)fieldValue; break;
			case 2: this.DecimalValue = (System.Byte[])fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
